package server.database;

public enum RequestType {
    ADD_EVENT, REMOVE_EVENT, LIST_EVENT_AVAILABILITY, BOOK_EVENT, GET_BOOKING_SCHEDULE, CANCEL_EVENT, SWAP_EVENT, CHECK_CAPACITY, CHECK_IS_REGISTERED, GET_TOTAL_EVENTS
}
